/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yahtzee;

/**
 *
 * @author Tim
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnePlayer = new javax.swing.JButton();
        TwoPlayer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(250, 200));
        setMinimumSize(new java.awt.Dimension(250, 200));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        OnePlayer.setBackground(new java.awt.Color(153, 153, 153));
        OnePlayer.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        OnePlayer.setText("One Player");
        OnePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnePlayerActionPerformed(evt);
            }
        });
        getContentPane().add(OnePlayer);
        OnePlayer.setBounds(65, 100, 120, 29);

        TwoPlayer.setBackground(new java.awt.Color(153, 153, 153));
        TwoPlayer.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        TwoPlayer.setText("Two Players");
        TwoPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoPlayerActionPerformed(evt);
            }
        });
        getContentPane().add(TwoPlayer);
        TwoPlayer.setBounds(65, 130, 120, 29);

        jLabel3.setFont(new java.awt.Font("LiSong Pro", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("YAHTZEE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(14, 10, 220, 50);

        jLabel2.setFont(new java.awt.Font("LiSong Pro", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("How many players?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 70, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1280x1024-up-maroon-solid-color-background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 250, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnePlayerActionPerformed

        OnePlayer a = new OnePlayer();
        a.setVisible(true);
        
        a.Winner1.setVisible(false);
        a.Winner.setVisible(false);
        
        a.indicatorDieOne.setVisible(false);
        a.indicatorDieTwo.setVisible(false);
        a.indicatorDieThree.setVisible(false);
        a.indicatorDieFour.setVisible(false);
        a.indicatorDieFive.setVisible(false);
        
        a.Table.setRowSelectionAllowed(false);
        a.Table.setColumnSelectionAllowed(false); 
        a.Table.setFocusable(false);
        a.Table.setCellSelectionEnabled(false);
        
        a.Winner1.setVisible(false);
        
        a.disableAllDieButtons();
        a.disableAllButtonsInTable();
    }//GEN-LAST:event_OnePlayerActionPerformed

    private void TwoPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoPlayerActionPerformed
        TwoPlayer a = new TwoPlayer();
        a.setVisible(true);
        
        a.indicatorDieOne.setVisible(false);
        a.indicatorDieTwo.setVisible(false);
        a.indicatorDieThree.setVisible(false);
        a.indicatorDieFour.setVisible(false);
        a.indicatorDieFive.setVisible(false);
        
        a.Table.setRowSelectionAllowed(false);
        a.Table.setColumnSelectionAllowed(false); 
        a.Table.setFocusable(false);
        a.Table.setCellSelectionEnabled(false);
        
        a.disableAllDieButtons();
        a.disableAllButtonsInTable();
        

    }//GEN-LAST:event_TwoPlayerActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OnePlayer;
    private javax.swing.JButton TwoPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
