/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yahtzee;
import java.util.ArrayList;
/**
 *
 * @author Tim
 */
public class OnePlayer extends javax.swing.JFrame {     
    public OnePlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnesTextYou = new javax.swing.JLabel();
        TwosTextYou = new javax.swing.JLabel();
        ThreesTextYou = new javax.swing.JLabel();
        FoursTextYou = new javax.swing.JLabel();
        FivesTextYou = new javax.swing.JLabel();
        SixesTextYou = new javax.swing.JLabel();
        SumTextYou = new javax.swing.JLabel();
        BonusTextYou = new javax.swing.JLabel();
        ThreeOfAKindTextYou = new javax.swing.JLabel();
        FourOfAKindTextYou = new javax.swing.JLabel();
        FullHouseTextYou = new javax.swing.JLabel();
        SmallStraightTextYou = new javax.swing.JLabel();
        LargeStraightTextYou = new javax.swing.JLabel();
        ChanceTextYou = new javax.swing.JLabel();
        YahtzeeTextYou = new javax.swing.JLabel();
        TotalScoreTextYou = new javax.swing.JLabel();
        OnesYou = new javax.swing.JButton();
        TwosYou = new javax.swing.JButton();
        ThreesYou = new javax.swing.JButton();
        FoursYou = new javax.swing.JButton();
        FivesYou = new javax.swing.JButton();
        SixesYou = new javax.swing.JButton();
        ThreeKindYou = new javax.swing.JButton();
        FourKindYou = new javax.swing.JButton();
        FullHouseYou = new javax.swing.JButton();
        SmallStraightYou = new javax.swing.JButton();
        LargeStraightYou = new javax.swing.JButton();
        ChanceYou = new javax.swing.JButton();
        YahtzeeYou = new javax.swing.JButton();
        Rules = new javax.swing.JButton();
        Author = new javax.swing.JLabel();
        FirstDie = new javax.swing.JButton();
        SecondDie = new javax.swing.JButton();
        ThirdDie = new javax.swing.JButton();
        FourthDie = new javax.swing.JButton();
        FifthDie = new javax.swing.JButton();
        One = new javax.swing.JLabel();
        Two = new javax.swing.JLabel();
        Three = new javax.swing.JLabel();
        Four = new javax.swing.JLabel();
        Five = new javax.swing.JLabel();
        Six = new javax.swing.JLabel();
        One1 = new javax.swing.JLabel();
        Two1 = new javax.swing.JLabel();
        Three1 = new javax.swing.JLabel();
        Four1 = new javax.swing.JLabel();
        Five1 = new javax.swing.JLabel();
        Six1 = new javax.swing.JLabel();
        One2 = new javax.swing.JLabel();
        Two2 = new javax.swing.JLabel();
        Three2 = new javax.swing.JLabel();
        Four2 = new javax.swing.JLabel();
        Five2 = new javax.swing.JLabel();
        Six2 = new javax.swing.JLabel();
        One3 = new javax.swing.JLabel();
        Two3 = new javax.swing.JLabel();
        Three3 = new javax.swing.JLabel();
        Four3 = new javax.swing.JLabel();
        Five3 = new javax.swing.JLabel();
        Six3 = new javax.swing.JLabel();
        One4 = new javax.swing.JLabel();
        Two4 = new javax.swing.JLabel();
        Three4 = new javax.swing.JLabel();
        Four4 = new javax.swing.JLabel();
        Five4 = new javax.swing.JLabel();
        Six4 = new javax.swing.JLabel();
        indicatorDieOne = new javax.swing.JPanel();
        indicatorDieTwo = new javax.swing.JPanel();
        indicatorDieThree = new javax.swing.JPanel();
        indicatorDieFour = new javax.swing.JPanel();
        indicatorDieFive = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        RollsLeft = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Winner = new javax.swing.JScrollPane();
        Winner1 = new javax.swing.JTextArea();
        NewGame = new javax.swing.JButton();
        PastScores = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Roll = new javax.swing.JButton();
        Yahtzee = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yahtzee - Tim Gamble");
        setBounds(new java.awt.Rectangle(100, 100, 850, 600));
        setLocation(new java.awt.Point(200, 100));
        setMaximumSize(new java.awt.Dimension(790, 590));
        setMinimumSize(new java.awt.Dimension(790, 590));
        getContentPane().setLayout(null);

        OnesTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        OnesTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(OnesTextYou);
        OnesTextYou.setBounds(730, 30, 50, 30);

        TwosTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        TwosTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(TwosTextYou);
        TwosTextYou.setBounds(730, 60, 50, 30);

        ThreesTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        ThreesTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(ThreesTextYou);
        ThreesTextYou.setBounds(730, 90, 50, 30);

        FoursTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        FoursTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(FoursTextYou);
        FoursTextYou.setBounds(730, 120, 50, 30);

        FivesTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        FivesTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(FivesTextYou);
        FivesTextYou.setBounds(730, 150, 50, 30);

        SixesTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        SixesTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(SixesTextYou);
        SixesTextYou.setBounds(730, 180, 50, 30);

        SumTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13)); // NOI18N
        getContentPane().add(SumTextYou);
        SumTextYou.setBounds(730, 210, 50, 30);

        BonusTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13)); // NOI18N
        getContentPane().add(BonusTextYou);
        BonusTextYou.setBounds(730, 240, 50, 30);

        ThreeOfAKindTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        ThreeOfAKindTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(ThreeOfAKindTextYou);
        ThreeOfAKindTextYou.setBounds(730, 270, 50, 30);

        FourOfAKindTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        FourOfAKindTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(FourOfAKindTextYou);
        FourOfAKindTextYou.setBounds(730, 300, 50, 30);

        FullHouseTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        FullHouseTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(FullHouseTextYou);
        FullHouseTextYou.setBounds(730, 330, 50, 30);

        SmallStraightTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        SmallStraightTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(SmallStraightTextYou);
        SmallStraightTextYou.setBounds(730, 360, 50, 30);

        LargeStraightTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        LargeStraightTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(LargeStraightTextYou);
        LargeStraightTextYou.setBounds(730, 390, 50, 30);

        ChanceTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        ChanceTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(ChanceTextYou);
        ChanceTextYou.setBounds(730, 420, 50, 30);

        YahtzeeTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        YahtzeeTextYou.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(YahtzeeTextYou);
        YahtzeeTextYou.setBounds(730, 450, 50, 30);

        TotalScoreTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13)); // NOI18N
        getContentPane().add(TotalScoreTextYou);
        TotalScoreTextYou.setBounds(730, 480, 50, 30);

        OnesYou.setBorderPainted(false);
        OnesYou.setContentAreaFilled(false);
        OnesYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnesYouActionPerformed(evt);
            }
        });
        getContentPane().add(OnesYou);
        OnesYou.setBounds(610, 30, 160, 20);

        TwosYou.setBorderPainted(false);
        TwosYou.setContentAreaFilled(false);
        TwosYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwosYouActionPerformed(evt);
            }
        });
        getContentPane().add(TwosYou);
        TwosYou.setBounds(610, 60, 160, 20);

        ThreesYou.setBorderPainted(false);
        ThreesYou.setContentAreaFilled(false);
        ThreesYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreesYouActionPerformed(evt);
            }
        });
        getContentPane().add(ThreesYou);
        ThreesYou.setBounds(610, 90, 160, 20);

        FoursYou.setBorderPainted(false);
        FoursYou.setContentAreaFilled(false);
        FoursYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoursYouActionPerformed(evt);
            }
        });
        getContentPane().add(FoursYou);
        FoursYou.setBounds(610, 120, 160, 20);

        FivesYou.setBorderPainted(false);
        FivesYou.setContentAreaFilled(false);
        FivesYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FivesYouActionPerformed(evt);
            }
        });
        getContentPane().add(FivesYou);
        FivesYou.setBounds(610, 150, 160, 20);

        SixesYou.setBorderPainted(false);
        SixesYou.setContentAreaFilled(false);
        SixesYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixesYouActionPerformed(evt);
            }
        });
        getContentPane().add(SixesYou);
        SixesYou.setBounds(610, 180, 160, 20);

        ThreeKindYou.setBorderPainted(false);
        ThreeKindYou.setContentAreaFilled(false);
        ThreeKindYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeKindYouActionPerformed(evt);
            }
        });
        getContentPane().add(ThreeKindYou);
        ThreeKindYou.setBounds(610, 270, 160, 20);

        FourKindYou.setBorderPainted(false);
        FourKindYou.setContentAreaFilled(false);
        FourKindYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourKindYouActionPerformed(evt);
            }
        });
        getContentPane().add(FourKindYou);
        FourKindYou.setBounds(610, 300, 160, 20);

        FullHouseYou.setBorderPainted(false);
        FullHouseYou.setContentAreaFilled(false);
        FullHouseYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullHouseYouActionPerformed(evt);
            }
        });
        getContentPane().add(FullHouseYou);
        FullHouseYou.setBounds(610, 330, 160, 20);

        SmallStraightYou.setBorderPainted(false);
        SmallStraightYou.setContentAreaFilled(false);
        SmallStraightYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallStraightYouActionPerformed(evt);
            }
        });
        getContentPane().add(SmallStraightYou);
        SmallStraightYou.setBounds(610, 360, 160, 20);

        LargeStraightYou.setBorderPainted(false);
        LargeStraightYou.setContentAreaFilled(false);
        LargeStraightYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargeStraightYouActionPerformed(evt);
            }
        });
        getContentPane().add(LargeStraightYou);
        LargeStraightYou.setBounds(610, 390, 160, 20);

        ChanceYou.setBorderPainted(false);
        ChanceYou.setContentAreaFilled(false);
        ChanceYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChanceYouActionPerformed(evt);
            }
        });
        getContentPane().add(ChanceYou);
        ChanceYou.setBounds(610, 420, 160, 20);

        YahtzeeYou.setBorderPainted(false);
        YahtzeeYou.setContentAreaFilled(false);
        YahtzeeYou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YahtzeeYouActionPerformed(evt);
            }
        });
        getContentPane().add(YahtzeeYou);
        YahtzeeYou.setBounds(610, 450, 160, 20);

        Rules.setBackground(new java.awt.Color(153, 153, 153));
        Rules.setFont(new java.awt.Font("LiSong Pro", 0, 12)); // NOI18N
        Rules.setText("Rules");
        Rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesActionPerformed(evt);
            }
        });
        getContentPane().add(Rules);
        Rules.setBounds(615, 530, 160, 29);

        Author.setBackground(new java.awt.Color(153, 153, 153));
        Author.setForeground(new java.awt.Color(153, 153, 153));
        Author.setText("Tim Gamble");
        getContentPane().add(Author);
        Author.setBounds(258, 100, 80, 16);

        FirstDie.setBorderPainted(false);
        FirstDie.setContentAreaFilled(false);
        FirstDie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstDieActionPerformed(evt);
            }
        });
        getContentPane().add(FirstDie);
        FirstDie.setBounds(30, 290, 97, 90);

        SecondDie.setBorderPainted(false);
        SecondDie.setContentAreaFilled(false);
        SecondDie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondDieActionPerformed(evt);
            }
        });
        getContentPane().add(SecondDie);
        SecondDie.setBounds(140, 290, 97, 90);

        ThirdDie.setBorderPainted(false);
        ThirdDie.setContentAreaFilled(false);
        ThirdDie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdDieActionPerformed(evt);
            }
        });
        getContentPane().add(ThirdDie);
        ThirdDie.setBounds(250, 290, 97, 90);

        FourthDie.setBorderPainted(false);
        FourthDie.setContentAreaFilled(false);
        FourthDie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourthDieActionPerformed(evt);
            }
        });
        getContentPane().add(FourthDie);
        FourthDie.setBounds(360, 290, 97, 90);

        FifthDie.setBorderPainted(false);
        FifthDie.setContentAreaFilled(false);
        FifthDie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FifthDieActionPerformed(evt);
            }
        });
        getContentPane().add(FifthDie);
        FifthDie.setBounds(470, 290, 97, 90);

        One.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice1.png"))); // NOI18N
        getContentPane().add(One);
        One.setBounds(30, 280, 100, 110);

        Two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice2.png"))); // NOI18N
        getContentPane().add(Two);
        Two.setBounds(30, 280, 100, 110);

        Three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice3.png"))); // NOI18N
        getContentPane().add(Three);
        Three.setBounds(30, 280, 100, 110);

        Four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice4.png"))); // NOI18N
        getContentPane().add(Four);
        Four.setBounds(30, 280, 100, 110);

        Five.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice5.png"))); // NOI18N
        getContentPane().add(Five);
        Five.setBounds(30, 280, 100, 110);

        Six.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice6.png"))); // NOI18N
        getContentPane().add(Six);
        Six.setBounds(30, 280, 100, 110);

        One1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice1.png"))); // NOI18N
        getContentPane().add(One1);
        One1.setBounds(140, 280, 100, 110);

        Two1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice2.png"))); // NOI18N
        getContentPane().add(Two1);
        Two1.setBounds(140, 280, 100, 110);

        Three1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice3.png"))); // NOI18N
        getContentPane().add(Three1);
        Three1.setBounds(140, 280, 100, 110);

        Four1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice4.png"))); // NOI18N
        getContentPane().add(Four1);
        Four1.setBounds(140, 280, 100, 110);

        Five1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice5.png"))); // NOI18N
        getContentPane().add(Five1);
        Five1.setBounds(140, 280, 100, 110);

        Six1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice6.png"))); // NOI18N
        getContentPane().add(Six1);
        Six1.setBounds(140, 280, 100, 110);

        One2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice1.png"))); // NOI18N
        getContentPane().add(One2);
        One2.setBounds(250, 280, 100, 110);

        Two2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice2.png"))); // NOI18N
        getContentPane().add(Two2);
        Two2.setBounds(250, 280, 100, 110);

        Three2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice3.png"))); // NOI18N
        getContentPane().add(Three2);
        Three2.setBounds(250, 280, 100, 110);

        Four2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice4.png"))); // NOI18N
        getContentPane().add(Four2);
        Four2.setBounds(250, 280, 100, 110);

        Five2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice5.png"))); // NOI18N
        getContentPane().add(Five2);
        Five2.setBounds(250, 280, 100, 110);

        Six2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice6.png"))); // NOI18N
        getContentPane().add(Six2);
        Six2.setBounds(250, 280, 100, 110);

        One3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice1.png"))); // NOI18N
        getContentPane().add(One3);
        One3.setBounds(360, 280, 100, 110);

        Two3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice2.png"))); // NOI18N
        getContentPane().add(Two3);
        Two3.setBounds(360, 280, 100, 110);

        Three3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice3.png"))); // NOI18N
        getContentPane().add(Three3);
        Three3.setBounds(360, 280, 100, 110);

        Four3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice4.png"))); // NOI18N
        getContentPane().add(Four3);
        Four3.setBounds(360, 280, 100, 110);

        Five3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice5.png"))); // NOI18N
        getContentPane().add(Five3);
        Five3.setBounds(360, 280, 100, 110);

        Six3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice6.png"))); // NOI18N
        getContentPane().add(Six3);
        Six3.setBounds(360, 280, 100, 110);

        One4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice1.png"))); // NOI18N
        getContentPane().add(One4);
        One4.setBounds(470, 280, 100, 110);

        Two4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice2.png"))); // NOI18N
        getContentPane().add(Two4);
        Two4.setBounds(470, 280, 100, 110);

        Three4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice3.png"))); // NOI18N
        getContentPane().add(Three4);
        Three4.setBounds(470, 280, 100, 110);

        Four4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice4.png"))); // NOI18N
        getContentPane().add(Four4);
        Four4.setBounds(470, 280, 100, 110);

        Five4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice5.png"))); // NOI18N
        getContentPane().add(Five4);
        Five4.setBounds(470, 280, 100, 110);

        Six4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dice6.png"))); // NOI18N
        getContentPane().add(Six4);
        Six4.setBounds(470, 280, 100, 110);

        indicatorDieOne.setBackground(new java.awt.Color(153, 153, 153));
        indicatorDieOne.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(indicatorDieOne);
        indicatorDieOne.setBounds(64, 390, 30, 10);

        indicatorDieTwo.setBackground(new java.awt.Color(153, 153, 153));
        indicatorDieTwo.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(indicatorDieTwo);
        indicatorDieTwo.setBounds(174, 390, 30, 10);

        indicatorDieThree.setBackground(new java.awt.Color(153, 153, 153));
        indicatorDieThree.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(indicatorDieThree);
        indicatorDieThree.setBounds(284, 390, 30, 10);

        indicatorDieFour.setBackground(new java.awt.Color(153, 153, 153));
        indicatorDieFour.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(indicatorDieFour);
        indicatorDieFour.setBounds(394, 390, 30, 10);

        indicatorDieFive.setBackground(new java.awt.Color(153, 153, 153));
        indicatorDieFive.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(indicatorDieFive);
        indicatorDieFive.setBounds(504, 390, 30, 10);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setEnabled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 10, 170, 20);

        RollsLeft.setForeground(new java.awt.Color(153, 153, 153));
        RollsLeft.setText("Rolls Left: 3");
        getContentPane().add(RollsLeft);
        RollsLeft.setBounds(390, 445, 80, 16);

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Select the dice you want to keep.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(205, 490, 210, 16);

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Select your move by clicking one of the numbers in the table. ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 510, 390, 16);

        Winner.setBackground(new java.awt.Color(204, 0, 0));

        Winner1.setEditable(false);
        Winner1.setBackground(new java.awt.Color(153, 153, 153));
        Winner1.setColumns(1);
        Winner1.setFont(new java.awt.Font("LiSong Pro", 0, 16)); // NOI18N
        Winner1.setRows(1);
        Winner1.setBorder(null);
        Winner.setViewportView(Winner1);

        getContentPane().add(Winner);
        Winner.setBounds(176, 180, 244, 30);

        NewGame.setBackground(new java.awt.Color(153, 153, 153));
        NewGame.setFont(new java.awt.Font("LiSong Pro", 0, 12)); // NOI18N
        NewGame.setText("New Game");
        NewGame.setBounds(new java.awt.Rectangle(10, 30, 104, 29));
        NewGame.setMaximumSize(new java.awt.Dimension(106, 29));
        NewGame.setMinimumSize(new java.awt.Dimension(106, 29));
        NewGame.setPreferredSize(new java.awt.Dimension(106, 29));
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameActionPerformed(evt);
            }
        });
        getContentPane().add(NewGame);
        NewGame.setBounds(10, 30, 106, 29);

        PastScores.setBackground(new java.awt.Color(153, 153, 153));
        PastScores.setFont(new java.awt.Font("LiSong Pro", 0, 12)); // NOI18N
        PastScores.setText("Past Games");
        PastScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastScoresActionPerformed(evt);
            }
        });
        getContentPane().add(PastScores);
        PastScores.setBounds(10, 60, 106, 29);

        Table.setFont(new java.awt.Font("LiSong Pro", 0, 14)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ones", null},
                {"Twos", null},
                {"Threes", null},
                {"Fours", null},
                {"Fives", null},
                {"Sixes", null},
                {"Sum", null},
                {"Bonus", null},
                {"Three of a Kind", null},
                {"Four of a Kind", null},
                {"Full House", null},
                {"Small Straight", null},
                {"Large Straight", null},
                {"Chance", null},
                {"YAHTZEE", null},
                {"TOTAL SCORE", ""}
            },
            new String [] {
                "", "You"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.setToolTipText("");
        Table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Table.setAutoscrolls(false);
        Table.setEnabled(false);
        Table.setGridColor(new java.awt.Color(153, 153, 153));
        Table.setMaximumSize(new java.awt.Dimension(45, 480));
        Table.setRowHeight(30);
        Table.setRowSelectionAllowed(false);
        Table.setSelectionBackground(new java.awt.Color(102, 102, 102));
        Table.setSelectionForeground(new java.awt.Color(204, 204, 204));
        Table.setShowGrid(true);
        Table.setSize(new java.awt.Dimension(450, 65));
        jScrollPane1.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setResizable(false);
            Table.getColumnModel().getColumn(1).setResizable(false);
            Table.getColumnModel().getColumn(1).setPreferredWidth(3);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(610, 10, 170, 510);

        Roll.setBackground(new java.awt.Color(153, 153, 153));
        Roll.setFont(new java.awt.Font("LiSong Pro", 0, 24)); // NOI18N
        Roll.setText("Roll Dice");
        Roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollActionPerformed(evt);
            }
        });
        getContentPane().add(Roll);
        Roll.setBounds(215, 430, 170, 50);

        Yahtzee.setFont(new java.awt.Font("LiSong Pro", 1, 72)); // NOI18N
        Yahtzee.setForeground(new java.awt.Color(153, 153, 153));
        Yahtzee.setText("      YAHTZEE");
        getContentPane().add(Yahtzee);
        Yahtzee.setBounds(-7, 10, 610, 100);

        Background.setBackground(new java.awt.Color(204, 204, 204));
        Background.setForeground(new java.awt.Color(204, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1280x1024-up-maroon-solid-color-background.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 890, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    Actions a = new Actions();
    PastGames p = new PastGames();
    int firstDie = 0;
    int secondDie = 0;
    int thirdDie = 0;
    int fourthDie = 0;
    int fifthDie = 0;
    
    int first;
    int second;
    int third;
    int fourth;
    int fifth;
   
    int firstDie1;
    int secondDie1;
    int thirdDie1;
    int fourthDie1;
    int fifthDie1;
    
    int numTimesRollPressed = 0;
    
    int numTimesDieOnePressed = 0;
    int numTimesDieTwoPressed = 0;
    int numTimesDieThreePressed = 0;
    int numTimesDieFourPressed = 0;
    int numTimesDieFivePressed = 0;
    
    ArrayList<Integer> pastGames = new ArrayList();
    
    int onStartupCheck = 0;
    int max = 0;
    
    public void setText()
    {
        OnesTextYou.setText("");
        TwosTextYou.setText("");
        ThreesTextYou.setText("");
        FoursTextYou.setText("");
        FivesTextYou.setText("");
        SixesTextYou.setText("");
        
        ThreeOfAKindTextYou.setText("");
        FourOfAKindTextYou.setText("");
        FullHouseTextYou.setText("");
        SmallStraightTextYou.setText("");
        LargeStraightTextYou.setText("");
        ChanceTextYou.setText("");
        YahtzeeTextYou.setText("");
    }
    public void onStartUp()
    {
        Winner.setVisible(false);
        
        indicatorDieOne.setVisible(false);
        indicatorDieTwo.setVisible(false);
        indicatorDieThree.setVisible(false);
        indicatorDieFour.setVisible(false);
        indicatorDieFive.setVisible(false);
        
        Table.setRowSelectionAllowed(false);
        Table.setColumnSelectionAllowed(false); 
        Table.setFocusable(false);
        Table.setCellSelectionEnabled(false);

    }
    public void setVisibleFalse()
    {
        
        One.setVisible(false);
        Two.setVisible(false);
        Three.setVisible(false);
        Four.setVisible(false);
        Five.setVisible(false);
        Six.setVisible(false);
        
        One1.setVisible(false);
        Two1.setVisible(false);
        Three1.setVisible(false);
        Four1.setVisible(false);
        Five1.setVisible(false);
        Six1.setVisible(false);
        
        One2.setVisible(false);
        Two2.setVisible(false);
        Three2.setVisible(false);
        Four2.setVisible(false);
        Five2.setVisible(false);
        Six2.setVisible(false);
        
        One3.setVisible(false);
        Two3.setVisible(false);
        Three3.setVisible(false);
        Four3.setVisible(false);
        Five3.setVisible(false);
        Six3.setVisible(false);
        
        One4.setVisible(false);
        Two4.setVisible(false);
        Three4.setVisible(false);
        Four4.setVisible(false);
        Five4.setVisible(false);
        Six4.setVisible(false);
        
    }
    public void setVisibleTrue()
    {
        if(first == 0) One.setVisible(true);
        if(first == 1) Two.setVisible(true);
        if(first == 2) Three.setVisible(true);
        if(first == 3) Four.setVisible(true);
        if(first == 4) Five.setVisible(true);
        if(first == 5) Six.setVisible(true);
        
        if(second == 0) One1.setVisible(true);
        if(second == 1) Two1.setVisible(true);
        if(second == 2) Three1.setVisible(true);
        if(second == 3) Four1.setVisible(true);
        if(second == 4) Five1.setVisible(true);
        if(second == 5) Six1.setVisible(true);
        
        if(third == 0) One2.setVisible(true);
        if(third == 1) Two2.setVisible(true);
        if(third == 2) Three2.setVisible(true);
        if(third == 3) Four2.setVisible(true);
        if(third == 4) Five2.setVisible(true);
        if(third == 5) Six2.setVisible(true);
        
        if(fourth == 0) One3.setVisible(true);
        if(fourth == 1) Two3.setVisible(true);
        if(fourth == 2) Three3.setVisible(true);
        if(fourth == 3) Four3.setVisible(true);
        if(fourth == 4) Five3.setVisible(true);
        if(fourth == 5) Six3.setVisible(true);
        
        if(fifth == 0) One4.setVisible(true);
        if(fifth == 1) Two4.setVisible(true);
        if(fifth == 2) Three4.setVisible(true);
        if(fifth == 3) Four4.setVisible(true);
        if(fifth == 4) Five4.setVisible(true);
        if(fifth == 5) Six4.setVisible(true);
    }
    public void randomNumberMaker()
    {
        firstDie1 = (int)(Math.random()*6);
        secondDie1 = (int)(Math.random()*6);
        thirdDie1 = (int)(Math.random()*6);
        fourthDie1 = (int)(Math.random()*6);
        fifthDie1 = (int)(Math.random()*6);
    }
    public void addToArray()
    {
        if(firstDie==0) a.diceNumbers[0] = first;
        if(secondDie==0) a.diceNumbers[1] = second;
        if(thirdDie==0) a.diceNumbers[2] = third;
        if(fourthDie==0) a.diceNumbers[3] = fourth;
        if(fifthDie==0) a.diceNumbers[4] = fifth;
    }
    public void countEverything()
    {
        OnesTextYou.setText(OnesTextYou.getText() + a.countOnes());
        TwosTextYou.setText(TwosTextYou.getText() + a.countTwos());
        ThreesTextYou.setText(ThreesTextYou.getText() + a.countThrees());
        FoursTextYou.setText(FoursTextYou.getText() + a.countFours());
        FivesTextYou.setText(FivesTextYou.getText() + a.countFives());
        SixesTextYou.setText(SixesTextYou.getText() + a.countSixes());
        
        ThreeOfAKindTextYou.setText(ThreeOfAKindTextYou.getText() + a.countThreeOfAKind());
        FourOfAKindTextYou.setText(FourOfAKindTextYou.getText() + a.countFourOfAKind());
        FullHouseTextYou.setText(FullHouseTextYou.getText() + a.countFullHouse());
        SmallStraightTextYou.setText(SmallStraightTextYou.getText() + a.countSmallStraight());
        LargeStraightTextYou.setText(LargeStraightTextYou.getText() + a.countLargeStraight());
        ChanceTextYou.setText(ChanceTextYou.getText() + a.countChance());
        YahtzeeTextYou.setText(YahtzeeTextYou.getText() + a.countYahtzee()); 
    }
    public void resetForNextRoll()
    {
        numTimesRollPressed = 0;
        numTimesDieOnePressed = 0;
        numTimesDieTwoPressed = 0;
        numTimesDieThreePressed = 0;
        numTimesDieFourPressed = 0;
        numTimesDieFivePressed = 0;
        firstDie = 0;
        secondDie = 0;
        thirdDie = 0;
        fourthDie = 0;
        fifthDie = 0;
        Roll.setBackground(new java.awt.Color(204, 204, 204));
    }
    public void disableAllButtonsInTable()
    {
        OnesYou.setEnabled(false);
        TwosYou.setEnabled(false);
        ThreesYou.setEnabled(false);
        FoursYou.setEnabled(false);
        FivesYou.setEnabled(false);
        SixesYou.setEnabled(false);
        ThreeKindYou.setEnabled(false);
        FourKindYou.setEnabled(false);
        FullHouseYou.setEnabled(false);
        SmallStraightYou.setEnabled(false);
        LargeStraightYou.setEnabled(false);
        ChanceYou.setEnabled(false);
        YahtzeeYou.setEnabled(false);  
    }
    public void enableAllButtonsInTable()
    {
        OnesYou.setEnabled(true);
        TwosYou.setEnabled(true);
        ThreesYou.setEnabled(true);
        FoursYou.setEnabled(true);
        FivesYou.setEnabled(true);
        SixesYou.setEnabled(true);
        ThreeKindYou.setEnabled(true);
        FourKindYou.setEnabled(true);
        FullHouseYou.setEnabled(true);
        SmallStraightYou.setEnabled(true);
        LargeStraightYou.setEnabled(true);
        ChanceYou.setEnabled(true);
        YahtzeeYou.setEnabled(true);  
    }
    public void disableAllDieButtons()
    {
        FirstDie.setEnabled(false);
        SecondDie.setEnabled(false);
        ThirdDie.setEnabled(false);
        FourthDie.setEnabled(false);
        FifthDie.setEnabled(false);
    }
    public void enableAllDieButtons()
    {
        FirstDie.setEnabled(true);
        SecondDie.setEnabled(true);
        ThirdDie.setEnabled(true);
        FourthDie.setEnabled(true);
        FifthDie.setEnabled(true);
    }
    public void whenTableIsClicked()
    {
        indicatorDieOne.setVisible(false);
        indicatorDieTwo.setVisible(false);
        indicatorDieThree.setVisible(false);
        indicatorDieFour.setVisible(false);
        indicatorDieFive.setVisible(false);
    }
    public int checkIfHighScore()
    {
        for(int i = 0; i < pastGames.size(); i++)
        {
            if(max<pastGames.get(i)) max = pastGames.get(i);
        }
        return max;
    }
    public void ifHighScore(int a)
    {
        checkIfHighScore();
        if(a==max)
        {
            Winner.setVisible(true);
            Winner1.setVisible(true);
            Winner1.append(max + " is your new high score!");
        }
        else
        {
            Winner.setVisible(true);
            Winner1.setVisible(true);
            Winner1.append(max + " is still your high score.");
        }
    }
    public void restartGame()
    {
        setVisibleFalse();
        setText();
        onStartUp();
        disableAllDieButtons();
        disableAllButtonsInTable();
        a.ones = 0;
        a.twos = 0;
        a.threes = 0;
        a.fours = 0;
        a.fives = 0;
        a.sixes = 0;
        a.bonus = 0;
        a.threeOfAKind = 0;
        a.fourOfAKind = 0;
        a.fullHouse = 0;
        a.smallStraight = 0;
        a.largeStraight = 0;
        a.chance = 0;
        a.yahtzee = 0;
    
        a.youOnesFinalCheck = 0;
        a.youTwosFinalCheck = 0;
        a.youThreesFinalCheck = 0;
        a.youFoursFinalCheck = 0;
        a.youFivesFinalCheck = 0;
        a.youSixesFinalCheck = 0;
    
        a.youThreeOfAKindFinalCheck = 0;
        a.youFourOfAKindFinalCheck = 0;
        a.youFullHouseFinalCheck = 0;
        a.youSmallStraightFinalCheck = 0;
        a.youLargeStraightFinalCheck = 0;
        a.youChanceFinalCheck = 0;
        a.youYahtzeeFinalCheck = 0;
        first = 0;
        second = 0;
        third = 0;
        fourth = 0;
        fifth = 0;
        numTimesDieOnePressed = 0;
        numTimesDieTwoPressed = 0;
        numTimesDieThreePressed = 0;
        numTimesDieFourPressed = 0;
        numTimesDieFivePressed = 0;
        numTimesRollPressed = 0;
        setVisibleTrue();
        BonusTextYou.setText("");
        SumTextYou.setText("");
        TotalScoreTextYou.setText("");
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        Winner.setVisible(false);
        Winner1.setText("");
        RollsLeft.setText("Rolls Left: 3");
        resetTableNumbers();
    }
    public void disableButtonsUsed()
    {
        if(a.youOnesFinalCheck == 1) OnesYou.setEnabled(false);
        if(a.youTwosFinalCheck == 1) TwosYou.setEnabled(false);
        if(a.youThreesFinalCheck == 1) ThreesYou.setEnabled(false);
        if(a.youFoursFinalCheck == 1) FoursYou.setEnabled(false);
        if(a.youFivesFinalCheck == 1) FivesYou.setEnabled(false);
        if(a.youSixesFinalCheck == 1) SixesYou.setEnabled(false);
        if(a.youThreeOfAKindFinalCheck == 1) ThreeKindYou.setEnabled(false);
        if(a.youFourOfAKindFinalCheck == 1) FourKindYou.setEnabled(false);
        if(a.youFullHouseFinalCheck == 1) FullHouseYou.setEnabled(false);
        if(a.youSmallStraightFinalCheck == 1) SmallStraightYou.setEnabled(false);
        if(a.youLargeStraightFinalCheck == 1) LargeStraightYou.setEnabled(false);
        if(a.youChanceFinalCheck == 1) ChanceYou.setEnabled(false);
        if(a.youYahtzeeFinalCheck == 1) YahtzeeYou.setEnabled(false);  
    }
    public void resetTableNumbers()
    {
        OnesTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        OnesTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        TwosTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        TwosTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        ThreesTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        ThreesTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        FoursTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        FoursTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        FivesTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        FivesTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        SixesTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        SixesTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        ThreeOfAKindTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        ThreeOfAKindTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        FourOfAKindTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        FourOfAKindTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        FullHouseTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        FullHouseTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        SmallStraightTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        SmallStraightTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        LargeStraightTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        LargeStraightTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        ChanceTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        ChanceTextYou.setForeground(new java.awt.Color(204, 0, 0));
        
        YahtzeeTextYou.setFont(new java.awt.Font("LiSong Pro", 0, 13));
        YahtzeeTextYou.setForeground(new java.awt.Color(204, 0, 0));
    }
        
    private void RollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollActionPerformed
        if(numTimesRollPressed<3)
        {
            RollsLeft.setText("");
            RollsLeft.setText("Rolls Left: " + (2-numTimesRollPressed));
        }
        if(onStartupCheck == 0)
        {
            onStartUp();
            onStartupCheck++;
        }
        numTimesRollPressed++;
        if(numTimesRollPressed > 3)
        {
            Roll.setBackground(new java.awt.Color(0, 0, 0));
        }
        else
        {
            randomNumberMaker();
        
            if(firstDie == 0) first = firstDie1;
            if(secondDie == 0) second = secondDie1;
            if(thirdDie == 0) third = thirdDie1;
            if(fourthDie == 0) fourth = fourthDie1;
            if(fifthDie == 0) fifth = fifthDie1;
        
            addToArray();
            setText();
            setVisibleFalse();
            setVisibleTrue();
            countEverything();
            enableAllButtonsInTable();
            enableAllDieButtons();
            disableButtonsUsed();
        }
        if(a.checkIfYahtzee() && a.yahtzee > 0)
        {
            YahtzeeYou.setEnabled(true);
        }
    }//GEN-LAST:event_RollActionPerformed

    private void RulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesActionPerformed
        Rules help = new Rules();
        
        help.Page1.setVisible(true);
        help.Page2.setVisible(false);
        help.Page3.setVisible(false);
        help.Page4.setVisible(false);
        help.Page5.setVisible(false);
        help.Page6.setVisible(false);
        help.Page7.setVisible(false);
        help.Page8.setVisible(false);
        help.PageNumber.setVisible(true);
        
        help.setVisible(true);
    }//GEN-LAST:event_RulesActionPerformed

    private void FirstDieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstDieActionPerformed
        
        if(numTimesDieOnePressed%2 == 0)
        {
            firstDie = 1;
            indicatorDieOne.setVisible(true);
        }
        else if(numTimesDieOnePressed%2 == 1)
        {
            firstDie = 0;
            indicatorDieOne.setVisible(false);
        }
        numTimesDieOnePressed++;
    }//GEN-LAST:event_FirstDieActionPerformed

    private void SecondDieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondDieActionPerformed
        
        if(numTimesDieTwoPressed%2 == 0)
        {
            secondDie = 1;
            indicatorDieTwo.setVisible(true);
        }
        else if(numTimesDieTwoPressed%2 == 1)
        {
            secondDie = 0;
            indicatorDieTwo.setVisible(false);
        }
        numTimesDieTwoPressed++;
    }//GEN-LAST:event_SecondDieActionPerformed

    private void ThirdDieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdDieActionPerformed
        
        if(numTimesDieThreePressed%2 == 0)
        {
            thirdDie = 1;
            indicatorDieThree.setVisible(true);
        }
        else if(numTimesDieThreePressed%2 == 1)
        {
            thirdDie = 0;
            indicatorDieThree.setVisible(false);
        }
        numTimesDieThreePressed++;
    }//GEN-LAST:event_ThirdDieActionPerformed

    private void FourthDieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourthDieActionPerformed
        
        if(numTimesDieFourPressed%2 == 0)
        {
            fourthDie = 1;
            indicatorDieFour.setVisible(true);
        }
        else if(numTimesDieFourPressed%2 == 1)
        {
            fourthDie = 0;
            indicatorDieFour.setVisible(false);
        }
        numTimesDieFourPressed++;
    }//GEN-LAST:event_FourthDieActionPerformed

    private void FifthDieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FifthDieActionPerformed
        
        if(numTimesDieFivePressed%2 == 0)
        {
            fifthDie = 1;
            indicatorDieFive.setVisible(true);
        }
        else if(numTimesDieFivePressed%2 == 1)
        {
            fifthDie = 0;
            indicatorDieFive.setVisible(false);
        }
        numTimesDieFivePressed++;
    }//GEN-LAST:event_FifthDieActionPerformed

    public void ifCheck()
    {
        TotalScoreTextYou.setText(TotalScoreTextYou.getText() + a.findFinalScore());
        pastGames.add(a.findFinalScore());
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        disableAllButtonsInTable();
        disableAllDieButtons();
        ifHighScore(a.findFinalScore());
        numTimesRollPressed = 3;
        
        p.PastGamesText.setVisible(true);
        p.PastGamesText.setText(printPastGames());
    }
    
    private void OnesYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnesYouActionPerformed
        
        a.ones = a.countOnes();
        a.youOnesFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        OnesTextYou.setForeground(new java.awt.Color(0, 0, 0));
        OnesTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            SumTextYou.setText(SumTextYou.getText() + a.calculateSum());
            a.bonus();
            BonusTextYou.setText(BonusTextYou.getText() + a.bonus);
        }
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
        
    }//GEN-LAST:event_OnesYouActionPerformed

    private void TwosYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwosYouActionPerformed
        a.twos = a.countTwos();
        a.youTwosFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        TwosTextYou.setForeground(new java.awt.Color(0, 0, 0));
        TwosTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            SumTextYou.setText(SumTextYou.getText() + a.calculateSum());
            a.bonus();
            BonusTextYou.setText(BonusTextYou.getText() + a.bonus);
        }
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_TwosYouActionPerformed

    private void ThreesYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreesYouActionPerformed
        a.threes = a.countThrees();
        a.youThreesFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        ThreesTextYou.setForeground(new java.awt.Color(0, 0, 0));
        ThreesTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            SumTextYou.setText(SumTextYou.getText() + a.calculateSum());
            a.bonus();
            BonusTextYou.setText(BonusTextYou.getText() + a.bonus);
        }
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_ThreesYouActionPerformed

    private void FoursYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoursYouActionPerformed
        a.fours = a.countFours();
        a.youFoursFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        FoursTextYou.setForeground(new java.awt.Color(0, 0, 0));
        FoursTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            SumTextYou.setText(SumTextYou.getText() + a.calculateSum());
            a.bonus();
            BonusTextYou.setText(BonusTextYou.getText() + a.bonus);
        }
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_FoursYouActionPerformed

    private void FivesYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FivesYouActionPerformed
        a.fives = a.countFives();
        a.youFivesFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        FivesTextYou.setForeground(new java.awt.Color(0, 0, 0));
        FivesTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            SumTextYou.setText(SumTextYou.getText() + a.calculateSum());
            a.bonus();
            BonusTextYou.setText(BonusTextYou.getText() + a.bonus);
        }
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_FivesYouActionPerformed

    private void SixesYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixesYouActionPerformed
        a.sixes = a.countSixes();
        a.youSixesFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        SixesTextYou.setForeground(new java.awt.Color(0, 0, 0));
        SixesTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            SumTextYou.setText(SumTextYou.getText() + a.calculateSum());
            a.bonus();
            BonusTextYou.setText(BonusTextYou.getText() + a.bonus);
        }
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_SixesYouActionPerformed

    private void ThreeKindYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeKindYouActionPerformed
        a.threeOfAKind = a.countThreeOfAKind();
        a.youThreeOfAKindFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        ThreeOfAKindTextYou.setForeground(new java.awt.Color(0, 0, 0));
        ThreeOfAKindTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_ThreeKindYouActionPerformed

    private void FourKindYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourKindYouActionPerformed
        a.fourOfAKind = a.countFourOfAKind();
        a.youFourOfAKindFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        FourOfAKindTextYou.setForeground(new java.awt.Color(0, 0, 0));
        FourOfAKindTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_FourKindYouActionPerformed

    private void FullHouseYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullHouseYouActionPerformed
        a.fullHouse = a.countFullHouse();
        a.youFullHouseFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        FullHouseTextYou.setForeground(new java.awt.Color(0, 0, 0));
        FullHouseTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_FullHouseYouActionPerformed

    private void SmallStraightYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallStraightYouActionPerformed
        a.smallStraight = a.countSmallStraight();
        a.youSmallStraightFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        SmallStraightTextYou.setForeground(new java.awt.Color(0, 0, 0));
        SmallStraightTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_SmallStraightYouActionPerformed

    private void LargeStraightYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargeStraightYouActionPerformed
        a.largeStraight = a.countLargeStraight();
        a.youLargeStraightFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        LargeStraightTextYou.setForeground(new java.awt.Color(0, 0, 0));
        LargeStraightTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_LargeStraightYouActionPerformed

    private void ChanceYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChanceYouActionPerformed
        a.chance = a.countChance();
        a.youChanceFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        ChanceTextYou.setForeground(new java.awt.Color(0, 0, 0));
        ChanceTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_ChanceYouActionPerformed

    private void YahtzeeYouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YahtzeeYouActionPerformed
        if(a.checkIfYahtzee() && a.yahtzee > 0)
        {
            a.yahtzee = a.countYahtzee() + 100;
            YahtzeeTextYou.setText("");
            YahtzeeTextYou.setText(YahtzeeTextYou.getText() + a.yahtzee);
        }
        else
        {
            a.yahtzee = a.countYahtzee();
        }
        YahtzeeTextYou.setForeground(new java.awt.Color(0, 0, 0));
        YahtzeeTextYou.setFont(new java.awt.Font("LiHei Pro", 1, 13));
        a.youYahtzeeFinalCheck = 1;
        resetForNextRoll();
        disableAllButtonsInTable();
        disableAllDieButtons();
        whenTableIsClicked();
        Roll.setBackground(new java.awt.Color(204, 204, 204));
        if(a.youThreeOfAKindFinalCheck != 0 && a.youFourOfAKindFinalCheck != 0 && a.youFullHouseFinalCheck != 0 && 
                a.youSmallStraightFinalCheck != 0 && a.youLargeStraightFinalCheck != 0 && a.youChanceFinalCheck != 0 && 
                a.youYahtzeeFinalCheck != 0 && a.youOnesFinalCheck != 0 && a.youTwosFinalCheck != 0 && a.youThreesFinalCheck != 0 && 
                a.youFoursFinalCheck != 0 && a.youFivesFinalCheck != 0 && a.youSixesFinalCheck != 0)
        {
            ifCheck();
        }
        RollsLeft.setText("Rolls Left: 3");
    }//GEN-LAST:event_YahtzeeYouActionPerformed

    private void NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameActionPerformed
        restartGame();
    }//GEN-LAST:event_NewGameActionPerformed
 
    public String printPastGames()
    {
        String printMe = "";
        for(int i = 0; i < pastGames.size(); i++)
        {
            printMe+=i+1 + ". " + pastGames.get(i) + "\n";
        }
        return printMe;
    }
    private void PastScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastScoresActionPerformed
        
        p.setVisible(true);
        
        
    }//GEN-LAST:event_PastScoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnePlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BonusTextYou;
    private javax.swing.JLabel ChanceTextYou;
    private javax.swing.JButton ChanceYou;
    private javax.swing.JButton FifthDie;
    private javax.swing.JButton FirstDie;
    private javax.swing.JLabel Five;
    private javax.swing.JLabel Five1;
    private javax.swing.JLabel Five2;
    private javax.swing.JLabel Five3;
    private javax.swing.JLabel Five4;
    private javax.swing.JLabel FivesTextYou;
    private javax.swing.JButton FivesYou;
    private javax.swing.JLabel Four;
    private javax.swing.JLabel Four1;
    private javax.swing.JLabel Four2;
    private javax.swing.JLabel Four3;
    private javax.swing.JLabel Four4;
    private javax.swing.JButton FourKindYou;
    private javax.swing.JLabel FourOfAKindTextYou;
    private javax.swing.JLabel FoursTextYou;
    private javax.swing.JButton FoursYou;
    private javax.swing.JButton FourthDie;
    private javax.swing.JLabel FullHouseTextYou;
    private javax.swing.JButton FullHouseYou;
    private javax.swing.JLabel LargeStraightTextYou;
    private javax.swing.JButton LargeStraightYou;
    private javax.swing.JButton NewGame;
    private javax.swing.JLabel One;
    private javax.swing.JLabel One1;
    private javax.swing.JLabel One2;
    private javax.swing.JLabel One3;
    private javax.swing.JLabel One4;
    private javax.swing.JLabel OnesTextYou;
    private javax.swing.JButton OnesYou;
    private javax.swing.JButton PastScores;
    private javax.swing.JButton Roll;
    private javax.swing.JLabel RollsLeft;
    private javax.swing.JButton Rules;
    private javax.swing.JButton SecondDie;
    private javax.swing.JLabel Six;
    private javax.swing.JLabel Six1;
    private javax.swing.JLabel Six2;
    private javax.swing.JLabel Six3;
    private javax.swing.JLabel Six4;
    private javax.swing.JLabel SixesTextYou;
    private javax.swing.JButton SixesYou;
    private javax.swing.JLabel SmallStraightTextYou;
    private javax.swing.JButton SmallStraightYou;
    private javax.swing.JLabel SumTextYou;
    public javax.swing.JTable Table;
    private javax.swing.JButton ThirdDie;
    private javax.swing.JLabel Three;
    private javax.swing.JLabel Three1;
    private javax.swing.JLabel Three2;
    private javax.swing.JLabel Three3;
    private javax.swing.JLabel Three4;
    private javax.swing.JButton ThreeKindYou;
    private javax.swing.JLabel ThreeOfAKindTextYou;
    private javax.swing.JLabel ThreesTextYou;
    private javax.swing.JButton ThreesYou;
    private javax.swing.JLabel TotalScoreTextYou;
    private javax.swing.JLabel Two;
    private javax.swing.JLabel Two1;
    private javax.swing.JLabel Two2;
    private javax.swing.JLabel Two3;
    private javax.swing.JLabel Two4;
    private javax.swing.JLabel TwosTextYou;
    private javax.swing.JButton TwosYou;
    public javax.swing.JScrollPane Winner;
    public javax.swing.JTextArea Winner1;
    private javax.swing.JLabel Yahtzee;
    private javax.swing.JLabel YahtzeeTextYou;
    private javax.swing.JButton YahtzeeYou;
    public javax.swing.JPanel indicatorDieFive;
    public javax.swing.JPanel indicatorDieFour;
    public javax.swing.JPanel indicatorDieOne;
    public javax.swing.JPanel indicatorDieThree;
    public javax.swing.JPanel indicatorDieTwo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
