/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yahtzee;

/**
 *
 * @author Tim
 */
public class Rules extends javax.swing.JFrame {

    /**
     * Creates new form Rules
     */
    public Rules() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Next = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        PageNumber = new javax.swing.JLabel();
        Page1 = new javax.swing.JLabel();
        Page2 = new javax.swing.JLabel();
        Page3 = new javax.swing.JLabel();
        Page4 = new javax.swing.JLabel();
        Page5 = new javax.swing.JLabel();
        Page6 = new javax.swing.JLabel();
        Page7 = new javax.swing.JLabel();
        Page8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rules of Yahtzee - Tim Gamble");
        setBounds(new java.awt.Rectangle(0, 23, 530, 560));
        setMaximumSize(new java.awt.Dimension(530, 560));
        setMinimumSize(new java.awt.Dimension(530, 560));
        setSize(new java.awt.Dimension(530, 560));
        getContentPane().setLayout(null);

        Next.setBackground(new java.awt.Color(153, 153, 153));
        Next.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(0, 0, 75, 29);

        Previous.setBackground(new java.awt.Color(153, 153, 153));
        Previous.setFont(new java.awt.Font("LiSong Pro", 0, 13)); // NOI18N
        Previous.setText("Last");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });
        getContentPane().add(Previous);
        Previous.setBounds(0, 30, 75, 29);

        PageNumber.setFont(new java.awt.Font("LiHei Pro", 0, 18)); // NOI18N
        PageNumber.setForeground(new java.awt.Color(153, 153, 153));
        PageNumber.setText("1");
        getContentPane().add(PageNumber);
        PageNumber.setBounds(10, 510, 20, 20);

        Page1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yahtzee.png"))); // NOI18N
        getContentPane().add(Page1);
        Page1.setBounds(80, -30, 730, 600);

        Page2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yahtzee1.png"))); // NOI18N
        getContentPane().add(Page2);
        Page2.setBounds(80, -30, 480, 600);

        Page3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yahtzee2.png"))); // NOI18N
        getContentPane().add(Page3);
        Page3.setBounds(80, -30, 730, 600);

        Page4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yahtzee3.png"))); // NOI18N
        getContentPane().add(Page4);
        Page4.setBounds(80, -30, 730, 600);

        Page5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yahtzee4.png"))); // NOI18N
        getContentPane().add(Page5);
        Page5.setBounds(80, -30, 730, 600);

        Page6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yahtzee5.png"))); // NOI18N
        getContentPane().add(Page6);
        Page6.setBounds(80, -30, 730, 600);

        Page7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yahtzee6.png"))); // NOI18N
        getContentPane().add(Page7);
        Page7.setBounds(80, -30, 730, 600);

        Page8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yahtzee7.png"))); // NOI18N
        getContentPane().add(Page8);
        Page8.setBounds(80, -30, 730, 600);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1280x1024-up-maroon-solid-color-background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    int numTimesNextClicked = 0;
    
    public void setAllToFalse()
    {
        Page1.setVisible(false);
        Page2.setVisible(false);
        Page3.setVisible(false);
        Page4.setVisible(false);
        Page5.setVisible(false);
        Page6.setVisible(false);
        Page7.setVisible(false);
        Page8.setVisible(false);
        
    }
    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        if(numTimesNextClicked<7)
        {
            numTimesNextClicked++;
            PageNumber.setText(numTimesNextClicked+1+"");
        }
        if(numTimesNextClicked>-1 && numTimesNextClicked<8)
        {
            if(numTimesNextClicked == 1)
            {
            setAllToFalse();
            Page2.setVisible(true);
            }
            if(numTimesNextClicked == 2)
            {
            setAllToFalse();
            Page3.setVisible(true);
            }
            if(numTimesNextClicked == 3)
            {
            setAllToFalse();
            Page4.setVisible(true);
            }
            if(numTimesNextClicked == 4)
            {
            setAllToFalse();
            Page5.setVisible(true);
            }
            if(numTimesNextClicked == 5)
            {
            setAllToFalse();
            Page6.setVisible(true);
            }
            if(numTimesNextClicked == 6)
            {
            setAllToFalse();
            Page7.setVisible(true);
            }
            if(numTimesNextClicked == 7)
            {
            setAllToFalse();
            Page8.setVisible(true);
            }
        }
    }//GEN-LAST:event_NextActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        if(numTimesNextClicked > 0)
        {
            numTimesNextClicked--;
            PageNumber.setText(numTimesNextClicked+1+"");
        }
        if(numTimesNextClicked>-1 && numTimesNextClicked<8)
        {
            if(numTimesNextClicked == 0)
            {
                setAllToFalse();
                Page1.setVisible(true);
            }
            if(numTimesNextClicked == 1)
            {
            setAllToFalse();
            Page2.setVisible(true);
            }
            if(numTimesNextClicked == 2)
            {
            setAllToFalse();
            Page3.setVisible(true);
            }
            if(numTimesNextClicked == 3)
            {
            setAllToFalse();
            Page4.setVisible(true);
            }
            if(numTimesNextClicked == 4)
            {
            setAllToFalse();
            Page5.setVisible(true);
            }
            if(numTimesNextClicked == 5)
            {
            setAllToFalse();
            Page6.setVisible(true);
            }
            if(numTimesNextClicked == 6)
            {
            setAllToFalse();
            Page7.setVisible(true);
            }
            if(numTimesNextClicked == 7)
            {
            setAllToFalse();
            Page8.setVisible(true);
            }
        }
    }//GEN-LAST:event_PreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    public javax.swing.JLabel Page1;
    public javax.swing.JLabel Page2;
    public javax.swing.JLabel Page3;
    public javax.swing.JLabel Page4;
    public javax.swing.JLabel Page5;
    public javax.swing.JLabel Page6;
    public javax.swing.JLabel Page7;
    public javax.swing.JLabel Page8;
    public javax.swing.JLabel PageNumber;
    private javax.swing.JButton Previous;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
